common: &common
  adapter: postgresql
  username: apitest
  password: apitest

development:
  <<: *common
  database: apitest_development

test:
  <<: *common
  database: apitest_test

production:
  <<: *common
  database: apitest_production
